require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

inherit_from: .rubocop_todo.yml
