language: ruby

cache: bundler

before_install:
  - gem update --system

rvm:
  - 2.6.5
  - 2.4.0
  - 2.3.1
  - 2.2
  - 2.1.1
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
